package com.sampletest;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;
import org.springframework.web.client.RestTemplate;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        final RestTemplate template = new RestTemplate();
		String message = template.getForObject("http://localhost:8080/sample/hello", String.class);
        Assert.assertEquals("Hello Gradle", message);
    }
}
