package com.sampletest;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;
import org.springframework.web.client.RestTemplate;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        Library lib = new Library();
    	String msg = lib.someLibraryMethod();
    	Assert.assertEquals("Hello Gradle", msg);
    }
}
