package com.sample;

import javax.ws.rs.GET;
import javax.ws.rs.Path;

import org.springframework.stereotype.Component;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
@Path("/sample")
@Component
public class Library {
	
	@GET
	@Path("/hello")
    public String someLibraryMethod() {
        return "Hello Gradle";
    }
	
    public String chechNegative(){
	return "negative";
	}
}
